error: prepare to release 0.1.2
Added

- **TracedError**: `TracedError`, an error type wrapper that annotates
  an error with the current span.
- **SpanTrace**:`SpanTrace::status` method and `SpanTraceStatus` type
  for determing whether a `SpanTrace` was successfully captured (#614)

Changed

- **SpanTrace**: Made backtrace formatting more consistent with upstream
  changes to `std::backtrace` (#584)

Signed-off-by: Eliza Weisman <eliza@buoyant.io>