error: use intra-doc link
`ErrorLayer`'s docs linked to `SpanTrace` using a relative (`../`) path.
This works out wrong for the public re-export of `ErrorLayer` in the
crate root.

Change to an intra-doc link which rustdoc knows to resolve whether
rendering the doc comment for the crate root or for the mod actually
defining `ErrorLayer`.