attributes: Improve spans for body block
`tracing::instrument` expands to something approximately like this:

```
fn name() {//^0
  {//^1
    // span
    {//^2
      if false {}
      {//^3
        // actual statements from the body
      }
    }
  }
}
```

When the actual body contains errors, rustc will use all kinds of spans
to display those errors.

Currently, tracing will assign call-site spans to `^1`, `^2`, `^3` and the
spans from the real `{` to `^0`. This is a problem because rustc will
sometimes use the span from `^3` in syntax errors:

```
fn main() {
    let x:
}
```

```
error: expected type, found `}`
 --> src/main.rs:4:1
  |
3 |     let x:
  |          - while parsing the type for `x`
4 | }
  | ^ expected type

error: expected type, found `}`
 --> src/main.rs:1:1
  |
1 | #[tracing_attributes::instrument]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected type
2 | fn main() {
3 |     let x:
  |          - while parsing the type for `x`
  |
  = note: this error originates in the attribute macro `tracing_attributes::instrument` (in Nightly builds, run with -Z macro-backtrace for more info)
```

The first error is from pre-expansion parsing, while the second error
comes from post-expansion parsing and chas the bad span because rustc
tries to point at the `}` character.

After this change, the span will improve significantly.

```
error: expected type, found `}`
 --> src/main.rs:2:11
  |
2 |   fn main() {
  |  ___________^
3 | |     let x:
  | |          - while parsing the type for `x`
4 | | }
  | |_^ expected type
```

It's still not perfect because of limitations in `proc_macro::Group`
that do not allow assigning the open and close spans separately.
If that ever becomes available, syn should be able to use it
automatically and tracing would get the nice errors.

Because it's still not quite perfect after this change, errors will
still not be deduplicated and there will be two of them.