attributes: fix compile error generation
Previously, some compile errors generated by `tracing-attributes` on bad
inputs, such as for an invalid `skip` arg, would be generated as the
_entire_ output of the attribute. Since the attribute is invoked in item
position (to generate a function), this would result in invalid code,
and the compiler would emit a much more cryptic parse error rather than
the intended helpful error.

For example, this code

```rust
    #[instrument(skip(baz))]
    fn bad_skip(foo: usize) {}
```

would result in the compiler outputting this error:

```
error: macros that expand to items must be delimited with braces or followed by a semicolon
 --> tracing-attributes/tests/bad_skip.rs:3:19
  |
3 | #[instrument(skip(baz))]
  |                   ^^^
  |
help: change the delimiters to curly braces
  |
3 | #[instrument(skip( {a}))]
  |                    ^ ^
help: add a semicolon
  |
3 | #[instrument(skip(baz;))]
  |                      ^
```

which doesn't make a lot of sense.

This branch changes the `instrument` attribute so that a function
definition is always generated, and any compile errors due to bad input
are generated _inside_ that function definition. This means that the
compiler won't complain at us for generating a bad function definition
before it sees our `compile_error` macros.

For example, the code I showed above now results in this error:

```
error: attempting to skip non-existent parameter
 --> tracing-attributes/tests/bad_skip.rs:3:19
  |
3 | #[instrument(skip(baz))]
  |
```

Fixes #612

Signed-off-by: Eliza Weisman <eliza@buoyant.io>