tracing: rename the last dispatch -> dispatcher (#1191)
It was renamed everywhere in #1015, but until #1190 it wasn't possible
to enter this macro branch. Now it fails with the following:

```
   Compiling tracing v0.2.0 (/Users/ivan/projects/tracing/tracing)
error[E0433]: failed to resolve: maybe a missing crate `dispatcher`?
    --> /Users/ivan/projects/tracing/tracing/src/macros.rs:2351:21
     |
2351 |           if !$crate::dispatcher::has_been_set() {
     |                       ^^^^^^^^^^ maybe a missing crate `dispatcher`?
```

Co-authored-by: Eliza Weisman <eliza@buoyant.io>